# Build Anders, which both AndersAA and SFS link against.
LEVEL= ../../..
LIBRARYNAME= anders
# USEDLIBS= # bdd.a  profiler.a THIS MIGHT BE REALLY BAD REMEMBER TO COME BACK TO THIS
SHARED_LIBRARY= 1
LINK_LIBS_IN_SHARED= 1
DONT_BUILD_RELINKED= 1
ENABLE_OPTIMIZED= 1
include $(LEVEL)/Makefile.common
